import { notFound } from "next/navigation";
import { sql } from "@/lib/db";
import SignupForm from "./SignupForm";

// Force dynamic so visit counters and stale-page checks happen per-request.
export const dynamic = "force-dynamic";
export const revalidate = 0;

type RouteContext = { params: Promise<{ slug: string }> };

interface LandingPageRow {
  slug: string;
  title: string;
  html: string;
  status: string;
  validation_campaign_id: string | null;
  project_id: string | null;
}

export default async function PublicLandingPage({ params }: RouteContext) {
  const { slug } = await params;

  const rows = await sql<LandingPageRow[]>`
    SELECT slug, title, html, status, validation_campaign_id, project_id
    FROM landing_pages
    WHERE slug = ${slug}
    LIMIT 1
  `;

  const page = rows[0];
  if (!page) notFound();
  if (page.status !== "published") notFound();

  // Increment visit count. Fire-and-forget; we don't block render on this.
  sql`UPDATE landing_pages SET visits = visits + 1 WHERE slug = ${slug}`
    .catch(() => { /* best-effort */ });

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "linear-gradient(180deg, var(--bg) 0%, var(--bg-2) 50%, var(--bg) 100%)",
      }}
    >
      <main style={{ maxWidth: 720, margin: "0 auto", padding: "60px 24px" }}>
        <div
          // The HTML body is generated by Five Rails (Hormozi-style validation
          // copy). It's stored under our control via authenticated upsert, not
          // user input, so dangerouslySetInnerHTML is acceptable here.
          dangerouslySetInnerHTML={{ __html: page.html }}
          style={{ marginBottom: 40 }}
        />

        <div
          id="signup"
          style={{
            background: "rgba(99, 102, 241, 0.05)",
            border: "1px solid rgba(99, 102, 241, 0.3)",
            borderRadius: 16,
            padding: 28,
          }}
        >
          <h3 style={{ margin: "0 0 4px", fontSize: 18, fontWeight: 600 }}>Get early access</h3>
          <p style={{ margin: "0 0 20px", fontSize: 14, color: "var(--muted)" }}>
            Drop your email — we&apos;ll let you know the moment this is ready.
          </p>
          <SignupForm slug={slug} />
        </div>

        <p
          style={{
            marginTop: 32,
            fontSize: 10,
            textAlign: "center",
            textTransform: "uppercase",
            letterSpacing: "0.08em",
            color: "var(--dim)",
          }}
        >
          Validation test · {page.title}
        </p>
      </main>
    </div>
  );
}
